# Generated by Django 4.2.1 on 2023-05-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskId', models.CharField(blank=True, max_length=255, null=True)),
                ('Status', models.CharField(max_length=10)),
                ('Result', models.CharField(max_length=255, null=True)),
                ('StackTrace', models.TextField(null=True)),
                ('ResultDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
